import { CONFIRMATION_MODE_ENUM } from './_types'

export const CONFIRMATION_REGISTRATION_TARGET = '/api/confirmation/registration'
export const CONFIRMATION_AUTHORIZATION_TARGET = '/api/confirmation/authorization'

export const CONFIRMATION_REGISTRATION_PRIMARY_KEY = [
  CONFIRMATION_REGISTRATION_TARGET,
  'confirmation-registration-query',
]

export const CONFIRMATION_AUTHORIZATION_PRIMARY_KEY = [
  CONFIRMATION_AUTHORIZATION_TARGET,
  'confirmation-authorization-query',
]

export const CONFIRMATION_TARGET = {
  [CONFIRMATION_MODE_ENUM.REGISTRATION]: CONFIRMATION_REGISTRATION_TARGET,
  [CONFIRMATION_MODE_ENUM.AUTHORIZATION]: CONFIRMATION_AUTHORIZATION_TARGET,
}

export const CONFIRMATION_PRIMARY_KEY = {
  [CONFIRMATION_MODE_ENUM.REGISTRATION]: CONFIRMATION_REGISTRATION_PRIMARY_KEY,
  [CONFIRMATION_MODE_ENUM.AUTHORIZATION]: CONFIRMATION_AUTHORIZATION_PRIMARY_KEY,
}
