import { CONFIRMATION_MODE_ENUM } from './_types'

export const CONFIRMATION_REGISTRATION_TARGET = '/api/confirmation/registration'
export const CONFIRMATION_AUTHORIZATION_TARGET = '/api/confirmation/authorization'
export const CONFIRMATION_RESET_PASSWORD_TARGET = '/api/confirmation/reset_password'
export const CONFIRMATION_RECOVERY_PASSWORD_TARGET = '/api/confirmation/recovery_password'

export const CONFIRMATION_REGISTRATION_PRIMARY_KEY = [
  CONFIRMATION_REGISTRATION_TARGET,
  'confirmation-registration-query',
]

export const CONFIRMATION_AUTHORIZATION_PRIMARY_KEY = [
  CONFIRMATION_AUTHORIZATION_TARGET,
  'confirmation-authorization-query',
]

export const CONFIRMATION_RESET_PASSWORD_PRIMARY_KEY = [
  CONFIRMATION_AUTHORIZATION_TARGET,
  'confirmation-reset-password-query',
]

export const CONFIRMATION_RECOVERY_PASSWORD_PRIMARY_KEY = [
  CONFIRMATION_AUTHORIZATION_TARGET,
  'confirmation-recovery-password-query',
]

export const CONFIRMATION_TARGET = {
  [CONFIRMATION_MODE_ENUM.REGISTRATION]: CONFIRMATION_REGISTRATION_TARGET,
  [CONFIRMATION_MODE_ENUM.AUTHORIZATION]: CONFIRMATION_AUTHORIZATION_TARGET,
  [CONFIRMATION_MODE_ENUM.RESET_PASSWORD]: CONFIRMATION_RESET_PASSWORD_TARGET,
  [CONFIRMATION_MODE_ENUM.RECOVERY_PASSWORD]: CONFIRMATION_RECOVERY_PASSWORD_TARGET,
}

export const CONFIRMATION_PRIMARY_KEY = {
  [CONFIRMATION_MODE_ENUM.REGISTRATION]: CONFIRMATION_REGISTRATION_PRIMARY_KEY,
  [CONFIRMATION_MODE_ENUM.AUTHORIZATION]: CONFIRMATION_AUTHORIZATION_PRIMARY_KEY,
  [CONFIRMATION_MODE_ENUM.RESET_PASSWORD]: CONFIRMATION_RESET_PASSWORD_PRIMARY_KEY,
  [CONFIRMATION_MODE_ENUM.RECOVERY_PASSWORD]: CONFIRMATION_RECOVERY_PASSWORD_PRIMARY_KEY,
}
